apiVersion: v1
kind: Service
metadata:
  name: kai-web
  namespace: kai-konane
  labels:
    app.kubernetes.io/name: kai-konane
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kai-konane
    app.kubernetes.io/component: web