from routes.admin_routes import admin_bp
from routes.feedback_routes import feedback_bp
from routes.preschool_routes import preschool_bp
from routes.user_routes import user_bp
from routes.activity_routes import activity_bp
from routes.learning_content_routes import learning_content_bp
from routes.story_routes import story_bp
from routes.profile_routes import profile_bp
from routes.learning_plan_routes import learning_plan_bp
from routes.progress_route import progress_bp