"""Update learning plan enum

Revision ID: fe01c243a712
Revises: 93d8c21fef6b
Create Date: 2024-10-20 07:14:49.945141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe01c243a712'
down_revision = '93d8c21fef6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learningContent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('type', sa.Enum('ACTIVITY', 'STORY', 'GAME', name='type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learningPlan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('science_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='science_level'), nullable=True),
    sa.Column('technology_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='technology_level'), nullable=True),
    sa.Column('engineering_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='engineering_level'), nullable=True),
    sa.Column('math_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='math_level'), nullable=True),
    sa.Column('story_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='story_level'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('learningplan')
    op.drop_table('learningcontent')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint('activity_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'learningContent', ['id'], ['id'])

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint('progress_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'learningContent', ['learning_content_id'], ['id'])

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_constraint('story_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'learningContent', ['id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('story_ibfk_1', 'learningcontent', ['id'], ['id'])

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('progress_ibfk_2', 'learningcontent', ['learning_content_id'], ['id'])

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activity_ibfk_1', 'learningcontent', ['id'], ['id'])

    op.create_table('learningcontent',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('type', mysql.ENUM('ACTIVITY', 'STORY', 'GAME'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('learningplan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('child_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('science_level', mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'), nullable=True),
    sa.Column('technology_level', mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'), nullable=True),
    sa.Column('engineering_level', mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'), nullable=True),
    sa.Column('math_level', mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'), nullable=True),
    sa.Column('story_level', mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name='learningplan_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('learningPlan')
    op.drop_table('learningContent')
    # ### end Alembic commands ###
