"""Update learning plan enum

Revision ID: fe01c243a712
Revises: 93d8c21fef6b
Create Date: 2024-10-20 07:14:49.945141

"""


# revision identifiers, used by Alembic.
revision = 'fe01c243a712'
down_revision = '93d8c21fef6b'
branch_labels = None
depends_on = None


def upgrade():
    """No-op on PostgreSQL.

    This migration was autogenerated against MySQL -- note the mysql_engine
    and mysql_collate arguments, and the activity_ibfk_1 constraint names,
    which are MySQL's auto-generated foreign key names.

    Its purpose there was a rename: MySQL's initial migration produced
    lowercase table names (learningcontent, learningplan), and this recreated
    them in camelCase and dropped the originals.

    On PostgreSQL the initial migration already creates "learningContent" and
    "learningPlan" in camelCase, with the three foreign keys to
    learningContent.id already in place. So every statement here is either a
    duplicate (CREATE TABLE on a table that exists) or a reference to
    something that never existed (DROP TABLE learningcontent, DROP CONSTRAINT
    activity_ibfk_1).

    Kept as a no-op rather than deleted so the revision chain stays intact:
    a1b2c3d4e5f6 has this as its down_revision.
    """
    pass


def downgrade():
    """No-op, matching upgrade."""
    pass
