"""Starter learning content.

Plain data, so adding an activity or a story is an edit here rather than a
code change. `flask seed` matches on title, which makes re-running it safe.

Every image referenced below already lives in static/images/.
"""

ACTIVITIES = [
    # ------------------------------------------------------------------ MATH
    {
        'title': 'Counting to Ten',
        'description': 'Count the things you see and pick the right number.',
        'stem_code': 'MATH',
        'level': 'BEGINNER',
        'cover_image': 'Basic_counting.jpeg',
        'questions': [
            {'content': 'How many fingers are on one hand?',
             'answers': [('Five', True), ('Three', False), ('Ten', False)]},
            {'content': 'You have 2 apples and pick up 1 more. How many now?',
             'answers': [('Three', True), ('Two', False), ('Four', False)]},
            {'content': 'Which number comes right after 6?',
             'answers': [('7', True), ('5', False), ('8', False)]},
        ],
    },
    {
        'title': 'Adding and Taking Away',
        'description': 'Simple addition and subtraction with small numbers.',
        'stem_code': 'MATH',
        'level': 'INTERMEDIATE',
        'cover_image': 'Basic_Addition_and_Sub.webp',
        'questions': [
            {'content': 'What is 4 + 3?',
             'answers': [('7', True), ('6', False), ('8', False)]},
            {'content': 'What is 9 - 5?',
             'answers': [('4', True), ('3', False), ('5', False)]},
            {'content': 'You had 10 sweets and ate 2. How many are left?',
             'answers': [('8', True), ('7', False), ('12', False)]},
        ],
    },
    {
        'title': 'Number Patterns',
        'description': 'Spot what comes next in a pattern.',
        'stem_code': 'MATH',
        'level': 'ADVANCED',
        'cover_image': 'Simple_Patterns.png',
        'questions': [
            {'content': 'What comes next? 2, 4, 6, 8, ...',
             'answers': [('10', True), ('9', False), ('12', False)]},
            {'content': 'What comes next? 5, 10, 15, ...',
             'answers': [('20', True), ('16', False), ('25', False)]},
            {'content': 'What comes next? red, blue, red, blue, ...',
             'answers': [('red', True), ('green', False), ('blue', False)]},
        ],
    },

    # --------------------------------------------------------------- SCIENCE
    {
        'title': 'Animals and Their Homes',
        'description': 'Match each animal to the place it lives.',
        'stem_code': 'SCIENCE',
        'level': 'BEGINNER',
        'cover_image': 'Animal_Habitats.webp',
        'questions': [
            {'content': 'Where does a fish live?',
             'answers': [('In the water', True), ('In a tree', False), ('Under a rock', False)]},
            {'content': 'Where does a bird build its nest?',
             'answers': [('In a tree', True), ('In the sea', False), ('In the sand', False)]},
            {'content': 'Which animal lives in a hive?',
             'answers': [('A bee', True), ('A dog', False), ('A frog', False)]},
        ],
    },
    {
        'title': 'What Is the Weather?',
        'description': 'Learn the words we use for different kinds of weather.',
        'stem_code': 'SCIENCE',
        'level': 'INTERMEDIATE',
        'cover_image': 'Weather_Matching.jpeg',
        'questions': [
            {'content': 'What do you need when it rains?',
             'answers': [('An umbrella', True), ('Sunglasses', False), ('A fan', False)]},
            {'content': 'What falls from the sky when it is very cold?',
             'answers': [('Snow', True), ('Sand', False), ('Leaves', False)]},
            {'content': 'What do we call it when the sun is shining?',
             'answers': [('Sunny', True), ('Windy', False), ('Cloudy', False)]},
        ],
    },
    {
        'title': 'Naming Animals',
        'description': 'Can you name the animal from the picture?',
        'stem_code': 'SCIENCE',
        'level': 'ADVANCED',
        'cover_image': 'Identify_Animals.png',
        'questions': [
            {'content': 'Which animal has a long trunk?',
             'answers': [('An elephant', True), ('A horse', False), ('A rabbit', False)]},
            {'content': 'Which animal changes from a caterpillar?',
             'answers': [('A butterfly', True), ('A spider', False), ('A beetle', False)]},
            {'content': 'Which animal hops and has long ears?',
             'answers': [('A rabbit', True), ('A cow', False), ('A duck', False)]},
        ],
    },

    # ------------------------------------------------------------ TECHNOLOGY
    {
        'title': 'Everyday Technology',
        'description': 'Find the machines we use every day.',
        'stem_code': 'TECHNOLOGY',
        'level': 'BEGINNER',
        'cover_image': 'Identifying_Everyday_Technology.png',
        'questions': [
            {'content': 'What do we use to keep food cold?',
             'answers': [('A fridge', True), ('A chair', False), ('A book', False)]},
            {'content': 'What do we use to call someone far away?',
             'answers': [('A phone', True), ('A spoon', False), ('A hat', False)]},
            {'content': 'What do we use to see a picture show at home?',
             'answers': [('A television', True), ('A pillow', False), ('A shoe', False)]},
        ],
    },
    {
        'title': 'What Does It Do?',
        'description': 'Match each machine to the job it does.',
        'stem_code': 'TECHNOLOGY',
        'level': 'INTERMEDIATE',
        'cover_image': 'Functions_Tech.avif',
        'questions': [
            {'content': 'What does a torch do?',
             'answers': [('It makes light', True), ('It makes ice', False), ('It makes noise', False)]},
            {'content': 'What does a clock do?',
             'answers': [('It tells the time', True), ('It cooks food', False), ('It cleans floors', False)]},
            {'content': 'What does a camera do?',
             'answers': [('It takes pictures', True), ('It plays music', False), ('It boils water', False)]},
        ],
    },
    {
        'title': 'Staying Safe with Technology',
        'description': 'Simple rules for using machines safely.',
        'stem_code': 'TECHNOLOGY',
        'level': 'ADVANCED',
        'cover_image': 'Technology_Safety.avif',
        'questions': [
            {'content': 'Who should you ask before using a new app?',
             'answers': [('A grown-up you trust', True), ('Nobody', False), ('A stranger online', False)]},
            {'content': 'What should you never share online?',
             'answers': [('Your home address', True), ('Your favourite colour', False), ('A drawing you made', False)]},
            {'content': 'What do you do if something online scares you?',
             'answers': [('Tell a grown-up', True), ('Keep it secret', False), ('Click it again', False)]},
        ],
    },

    # ----------------------------------------------------------- ENGINEERING
    {
        'title': 'Building with Shapes',
        'description': 'Which shapes make the strongest buildings?',
        'stem_code': 'ENGINEERING',
        'level': 'BEGINNER',
        'cover_image': 'Building_with_Shapes.jpg',
        'questions': [
            {'content': 'Which shape has three sides?',
             'answers': [('A triangle', True), ('A circle', False), ('A square', False)]},
            {'content': 'Which shape rolls best?',
             'answers': [('A circle', True), ('A square', False), ('A triangle', False)]},
            {'content': 'Which blocks are easiest to stack?',
             'answers': [('Flat square blocks', True), ('Round balls', False), ('Pointy cones', False)]},
        ],
    },
    {
        'title': 'Building a Bridge',
        'description': 'How do we make a bridge strong enough to cross?',
        'stem_code': 'ENGINEERING',
        'level': 'INTERMEDIATE',
        'cover_image': 'Bridge.jpg',
        'questions': [
            {'content': 'What does a bridge help us do?',
             'answers': [('Cross over water', True), ('Cook dinner', False), ('Tell the time', False)]},
            {'content': 'Which would make a stronger bridge?',
             'answers': [('A thick plank', True), ('A sheet of paper', False), ('A piece of string', False)]},
            {'content': 'What holds a bridge up?',
             'answers': [('Strong supports', True), ('Balloons', False), ('Feathers', False)]},
        ],
    },
    {
        'title': 'Simple Machines',
        'description': 'Ramps, wheels and levers make work easier.',
        'stem_code': 'ENGINEERING',
        'level': 'ADVANCED',
        'cover_image': 'Simple_Machines.webp',
        'questions': [
            {'content': 'What makes it easier to move a heavy box up?',
             'answers': [('A ramp', True), ('A wall', False), ('A hole', False)]},
            {'content': 'What do wheels help us do?',
             'answers': [('Roll things along', True), ('Keep things still', False), ('Make things heavy', False)]},
            {'content': 'A see-saw is an example of what?',
             'answers': [('A lever', True), ('A wheel', False), ('A screw', False)]},
        ],
    },
]


STORIES = [
    {
        'title': "Ben the Bear's Big Adventure",
        'description': 'Ben leaves his cave and discovers the whole forest.',
        'level': 'BEGINNER',
        'cover_page': 'BB_cover_page.png',
        'pages': [
            ('Ben was a little brown bear who lived in a big green forest.', 'BB_page_1.png'),
            ('One sunny morning, Ben decided to go on an adventure.', 'BB_page_2.png'),
            ('He walked past the tall trees and over the little stream.', 'BB_page_3.png'),
            ('Ben met a friendly rabbit who showed him the way.', 'BB_page_4.png'),
            ('They found a meadow full of bright flowers.', 'BB_page_5.png'),
            ('Ben and the rabbit played together all afternoon.', 'BB_page_6.png'),
            ('When the sun went down, Ben went home happy. The end.', 'BB_page_7.png'),
        ],
    },
    {
        'title': 'The Little Butterfly',
        'description': 'A caterpillar becomes a butterfly and learns to fly.',
        'level': 'BEGINNER',
        'cover_page': 'LB_cover_page.png',
        'pages': [
            ('A tiny caterpillar munched on a green leaf.', 'LB_page_1.png'),
            ('She ate and ate until she was big and round.', 'LB_page_2.png'),
            ('Then she made a little house around herself.', 'LB_page_3.png'),
            ('She slept inside for a long, quiet time.', 'LB_page_4.png'),
            ('One morning the little house opened up.', 'LB_page_5.png'),
            ('Out came a beautiful butterfly, and away she flew. The end.', 'LB_page_6.png'),
        ],
    },
    {
        'title': 'Jump, Rabbit, Jump!',
        'description': 'A rabbit learns that being small is its own kind of strong.',
        'level': 'BEGINNER',
        'cover_page': 'JR_cover_page.png',
        'pages': [
            ('There was once a grey rabbit with very long ears.', 'JR_page_1.png'),
            ('The rabbit loved to jump higher than anyone else.', 'JR_page_2.png'),
            ('He jumped over the flowers in the field.', 'JR_page_3.png'),
            ('He jumped over a big round stone.', 'JR_page_4.png'),
            ('But he could not jump over the tall fence.', 'JR_page_5.png'),
            ('So he found a small hole and squeezed through instead.', 'JR_page_6.png'),
            ('Being small can be useful too! The end.', 'JR_page_7.png'),
        ],
    },
    {
        'title': "Lily's Garden Adventure",
        'description': 'Lily plants a seed and waits for it to grow.',
        'level': 'INTERMEDIATE',
        'cover_page': 'L_cover_page.png',
        'pages': [
            ('Lily loved sitting in her grandmother\'s garden.', 'L_page_1.png'),
            ('One day she found a small brown seed on the path.', 'L_page_2.png'),
            ('She dug a little hole and planted it in the soil.', 'L_page_3.png'),
            ('Every day Lily gave the seed some water.', 'L_page_4.png'),
            ('At first nothing happened, and Lily waited patiently.', 'L_page_5.png'),
            ('Then one morning a tiny green shoot appeared.', 'L_page_6.png'),
            ('It grew into the brightest flower in the garden. The end.', 'L_page_7.png'),
        ],
    },
    {
        'title': 'Max the Brave Dog',
        'description': 'Max is scared of the dark until he finds the moon.',
        'level': 'INTERMEDIATE',
        'cover_page': 'MD_cover_page.png',
        'pages': [
            ('Max was a friendly dog with a bright red collar.', 'MD_page_1.png'),
            ('Max was brave all day long, but he did not like the dark.', 'MD_page_2.png'),
            ('One night he heard a strange noise in the garden.', 'MD_page_3.png'),
            ('Max took a deep breath and went outside to look.', 'MD_page_4.png'),
            ('The noise was only the wind moving the leaves.', 'MD_page_5.png'),
            ('Max looked up and saw the moon shining down on him.', 'MD_page_6.png'),
            ('After that, Max was never afraid of the dark again. The end.', 'MD_page_7.png'),
        ],
    },
    {
        'title': "Sam's Kite",
        'description': 'Sam learns that the wind is worth waiting for.',
        'level': 'INTERMEDIATE',
        'cover_page': 'SK_cover_page.png',
        'pages': [
            ('Sam was given a bright yellow kite for his birthday.', 'SK_page_1.png'),
            ('He ran to the top of the hill to fly it.', 'SK_page_2.png'),
            ('But the air was still, and the kite would not lift.', 'SK_page_3.png'),
            ('Sam sat down on the grass and waited.', 'SK_page_4.png'),
            ('Then a gentle breeze began to blow.', 'SK_page_5.png'),
            ('Sam ran, and the kite climbed high into the blue sky.', 'SK_page_6.png'),
            ('Good things are worth waiting for. The end.', 'SK_page_7.png'),
        ],
    },
    {
        'title': 'The Girl Who Walked to the Moon',
        'description': 'A quiet bedtime story about imagination.',
        'level': 'ADVANCED',
        'cover_page': 'LT_cover_page.png',
        'pages': [
            ('Every night, a girl called Luna watched the moon from her window.', 'LT_page_1.png'),
            ('She wondered what it would be like to walk all the way there.', 'LT_page_2.png'),
            ('One evening she took her umbrella and stepped outside.', 'LT_page_3.png'),
            ('The wind lifted her gently over the hills.', 'LT_page_4.png'),
            ('She floated past the stars, and they winked at her.', 'LT_page_5.png'),
            ('The moon was quiet and kind, and it knew her name.', 'LT_page_6.png'),
            ('When Luna woke in her own bed, she smiled. The end.', 'LT_page_7.png'),
        ],
    },
]
